import '../justfile'

set allow-duplicate-recipes

# Set custom search attributes need elasticsearch
[group('run')]
temporal:
  #!/usr/bin/env sh
  cd ../docker-compose
  docker compose --file docker-compose.yml down
  docker compose --file docker-compose.yml up -d
