import '../justfile'

set allow-duplicate-recipes

# alias for `up`
[group('dev-server-docker')]
@temporal:
  just up

# add custom search attributes
[group('run')]
@add:
  cargo run --bin client_operator_serivce
